USE [master]
GO
/****** Object:  Database [MyPet]    Script Date: 3/20/2025 8:14:13 PM ******/
CREATE DATABASE [MyPet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyPet', FILENAME = N'C:\Users\Manikanta.Siddappa\MyPet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyPet_log', FILENAME = N'C:\Users\Manikanta.Siddappa\MyPet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MyPet] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyPet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyPet] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyPet] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyPet] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyPet] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyPet] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyPet] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyPet] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyPet] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyPet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyPet] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyPet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyPet] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyPet] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyPet] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyPet] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MyPet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyPet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyPet] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyPet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyPet] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyPet] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyPet] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyPet] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MyPet] SET  MULTI_USER 
GO
ALTER DATABASE [MyPet] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyPet] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyPet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyPet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MyPet] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MyPet] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MyPet] SET QUERY_STORE = OFF
GO
USE [MyPet]
GO
/****** Object:  Table [dbo].[Pets]    Script Date: 3/20/2025 8:14:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pets](
	[pet_id] [int] IDENTITY(1,1) NOT NULL,
	[pet_name] [nvarchar](100) NOT NULL,
	[pet_photo] [nvarchar](255) NULL,
	[contact_details] [nvarchar](255) NOT NULL,
	[lost_location] [nvarchar](255) NOT NULL,
	[is_lost] [bit] NULL,
	[created_at] [datetime] NULL,
	[found_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[pet_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Pets] ADD  DEFAULT ((1)) FOR [is_lost]
GO
ALTER TABLE [dbo].[Pets] ADD  DEFAULT (getdate()) FOR [created_at]
GO
USE [master]
GO
ALTER DATABASE [MyPet] SET  READ_WRITE 
GO
